#!/bin/sh
feh --bg-fil "/home/hizmy/Imágenes/wwalls/ANIME.jpeg"
xscreensaver -no-splash &
xcompmgr &
slstatus &
# ID_TOUCHPAD=$(xinput | grep -i touchpad | awk '{print $6}' | cut -d '=' -f 2)
# xinput disable $ID_TOUCHPAD &
dwm 2> ~/.dwm.log
